DROP TABLE IF EXISTS BID,COURSE,COURSE_COMPLETED,PREREQUISITE,SECTION,STUDENT,SYSTEM_META,SUCCESSFULBID;
drop table if exists bid,course,course_completed,prerequisite,section,student,system_meta,successfulbid;

create table STUDENT(
USERID varchar(20) not null,
NAME varchar(50),
PASSWORD varchar(50),
SCHOOL varchar (10),
eDOLLAR double,
constraint STUDENT_PK primary key  (USERID));


create table COURSE(
COURSECODE varchar(10) NOT NULL,
SCHOOL varchar(5),
TITLE varchar(50),
DESCRIPTION varchar(500),
EXAMDATE varchar(50),
EXAMSTART varchar(50),
EXAMEND varchar(50),
constraint COURSE_PK primary key (COURSECODE));


create table SECTION(
COURSECODE varchar(10) not null,
SECTIONCODE varchar(10) not null,
DAY varchar(10),
START varchar(50),
END varchar(50),
INSTRUCTOR varchar(50),
VENUE varchar(50),
SIZE int,
CONSTRAINT SECTION_PK PRIMARY KEY (COURSECODE,SECTIONCODE));



create table BID(
USERID varchar(20) NOT NULL,
COURSECODE varchar(10) NOT NULL,
SECTIONCODE varchar(10) NOT NULL,
AMOUNT double,
CONSTRAINT BID_PK PRIMARY KEY (USERID,COURSECODE,SECTIONCODE));



CREATE TABLE COURSE_COMPLETED(
USERID varchar(20) NOT NULL,
COURSECODE varchar(10) NOT NULL,
CONSTRAINT COURSE_COMPLETED_PK PRIMARY KEY (USERID,COURSECODE));

create table SUCCESSFULBID(
USERID varchar(20) NOT NULL,
COURSECODE varchar(10) NOT NULL,
SECTIONCODE varchar(10) NOT NULL,
AMOUNT double,
CONSTRAINT SUCCESSFULBID_PK PRIMARY KEY (USERID,COURSECODE,SECTIONCODE));

CREATE TABLE PREREQUISITE(
COURSECODE VARCHAR(10) NOT NULL,
PREREQ_COURSECODE VARCHAR(10) NOT NULL,
CONSTRAINT PREREQUISITE_PK PRIMARY KEY(COURSECODE,PREREQ_COURSECODE));

CREATE TABLE SYSTEM_META(
ID int,
PROPERTY varchar(20) NOT NULL,
VALUE varchar(20) NOT NULL,
CONSTRAINT SYSTEM_META_PK PRIMARY KEY(PROPERTY,VALUE));

INSERT INTO SYSTEM_META(ID, PROPERTY, VALUE) VALUES(1, 'round1status', 'stopped');
INSERT INTO SYSTEM_META(ID, PROPERTY, VALUE) VALUES(2, 'round2status', 'stopped');
INSERT INTO SYSTEM_META(ID, PROPERTY, VALUE) VALUES(3, 'adminUsername', 'admin');
INSERT INTO SYSTEM_META(ID, PROPERTY, VALUE) VALUES(4, 'adminPassword', '123');
INSERT INTO SYSTEM_META(ID, PROPERTY, VALUE) VALUES(5, 'admin', '123');
